image: node:latest

stages:
  - install
  - build
  - validation
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - out/
lint:
  stage: validation
  dependencies:
    - install
  script:
    - npm run lint

test:
  stage: validation
  dependencies:
    - install
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
      when: on_success
      allow_failure: true

