stages: 
  - build
  - deploy

build:
  stage: build
  script:
    - npm run build
    - echo "Hello, $GITLAB_USER_LOGIN!"

deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."



