stages: 
  - build
  - run
  - deploy

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"


test-job1:
  stage: run
  script:
    - echo "This job tests something"

test-job2:
  stage: run
  script:
    - echo "This job tests something, but takes more time than test-job1."

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production


