image: node:latest

stages:
  - install
  - validation
  - build

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

prettier:
  stage: validation
  script:
    - npm run prettier

lint:
  stage: validation
  dependencies:
    - install
  script:
    - npm run lint

test:
  stage: validation
  dependencies:
    - install
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
  when: on_success
  allow_failure: true   #caso falhe, continuar a andar (impede que pare aqui)



