image: node:latest

stages:
  - install
  - validation
  - build
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: validation
  dependencies:
    - install
  script:
    - npm run lint

test:
  stage: validation
  dependencies:
    - install
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - out/
