version: 2.1

jobs:
  run_tests:  # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      - image: circleci/node:16.4 #all the node.js tools pre-installed

  #list of commands and things to do to execute
    steps:
      - checkout

      - run:
          name: Install npm dependencies
          command: 
            npm install --save

      - run:
          name: run lint
          command: 
            npm run lint

      - run:
          name: run prettier
          command: 
            npm run prettier

      - run:
          name: run jest
          command: 
            npm test --coverage

      - run:
          name: Build app
          command:
            npm run build

      - run:
          name: Deploy to Netlify
          command: 
            npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

workflows: #way to tie your jobs together so that they operate and function cohesively
  test_build_deply:
    jobs:
      - run_tests

