version: 2.1

jobs:
  run_test:   # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
  
    docker: #define docker key -> define docker image that will define where and how our code will run
      - image: circleci/node:16 #all the node.js tools pre-installed


    #list of commands and things to do to execute
    steps: 
      - checkout

      - run:
          name: Install npm dependencies
          command: 
            npm install --save

      - run:
          name: run lint
          command: 
            npm run lint

      - run:
          name: run prettier
          command:
            npm run prettier
      
      - run:
          name: run jest
          command:
            npm test

      - run: 
          name: run build
          command: Build app

workflows: #way to tie your jobs together so that they operate and function cohesively
  build-test:
    jobs:
      - run_tests