version: 2.1

jobs:
  run_test:   # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
  
    docker: #define docker key -> define docker image that will define where and how our code will run
      - image: circleci/node:16 #all the node.js tools pre-installed
    
    steps: #list of commands and things to do to execute
      - checkout

      - run:
          name: Install npm dependencies
          command: 
            npm install --save
      
      -run:
        name: run jest
        command:
          npm test

workflows: #way to tie your jobs together so that they operate and function cohesively
  build-test:
    jobs:
      - run_test